In [12]:
import fasttext.util

In [13]:
fasttext.util.download_model('ta', if_exists='ignore')  # English

'cc.ta.300.bin'

In [14]:
ft = fasttext.load_model('cc.ta.300.bin')

In [11]:
ft.get_word_vector('பள்ளி')

array([-2.07138658e-02, -1.08233422e-01,  8.64246711e-02, -3.88603681e-03,
       -2.33822837e-02, -5.32085709e-02,  7.82545730e-02,  1.84746664e-02,
       -1.94862578e-02,  2.73230970e-02, -2.71674665e-03, -2.83441171e-02,
       -1.59673598e-02, -8.13780166e-03,  4.37758118e-02, -1.29452512e-01,
       -4.93319593e-02, -7.74425268e-02,  8.85141492e-02,  4.18095253e-02,
        2.46369764e-02, -3.11867390e-02,  3.22013982e-02, -9.67689231e-02,
       -7.05196261e-02, -9.63690318e-03,  4.09294665e-02,  1.01436786e-02,
        7.92189501e-04,  3.93997692e-02,  3.72402966e-02,  2.02535633e-02,
        6.97395578e-02,  2.53558289e-02, -3.79315093e-02,  2.80181412e-02,
       -1.37251854e-01,  1.04167117e-02,  3.35209444e-02,  8.54814425e-03,
       -1.01716286e-02, -1.81007888e-02, -1.82577930e-02,  5.56269214e-02,
       -3.24874595e-02,  5.49678728e-02,  1.01667553e-01, -2.81709246e-03,
        4.82380204e-02, -9.16458853e-03,  3.25434729e-02, -1.28710642e-03,
        1.43677555e-02, -

In [146]:
import string

# load doc into memory
def load_doc(filename):
	# open the file as read only
	file = open(filename, 'r')
	# read all text
	text = file.read()
	# close the file
	file.close()
	return text

# turn a doc into clean tokens
def clean_doc(doc):
	# replace '--' with a space ' '
	doc = doc.replace('--', ' ')
	# split into tokens by white space
	tokens = doc.split()
	# remove punctuation from each token
	table = str.maketrans('', '', string.punctuation)
	tokens = [w.translate(table) for w in tokens]
	# remove remaining tokens that are not alphabetic
	#tokens = [word for word in tokens if word.isalpha()]
	# make lower case
	tokens = [word.lower() for word in tokens]
    # Strip all words
    #tokens = [word.strip() for word in tokens]
	return tokens

# save tokens to file, one dialog per line
def save_doc(lines, filename):
	data = '\n'.join(lines)
	file = open(filename, 'w')
	file.write(data)
	file.close()

# load document
in_filename = 'bharathi.txt'
doc = load_doc(in_filename)
print(doc[:200])

# clean document
tokens = clean_doc(doc)
print(tokens[:50])
print('Total Tokens: %d' % len(tokens))
print('Unique Tokens: %d' % len(set(tokens)))

# organize into sequences of tokens
length = 25 + 1
sequences = list()
for i in range(length, len(tokens)):
	# select sequence of tokens
	seq = tokens[i-length:i]
	# convert into a line
	line = ' '.join(seq)
	# store
	sequences.append(line)
print('Total Sequences: %d' % len(sequences))
print("Sample Sequences", sequences[0])

# save sequences to file
out_filename = 'bharathi_sequences.txt'
save_doc(sequences, out_filename)

அக்னி குஞ்சொன்று கண்டேன்....
அக்னி குஞ்சொன்று கண்டேன் - அதை 
அங்கொரு காட்டிலோர் பொந்திடை வைத்தேன்

அக்னி குஞ்சொன்று கண்டேன் - அதை 
அங்கொரு காட்டிலோர் பொந்திடை வைத்தேன்

வெந்து தணிந்தது காடு 
வெந்து தண
['அக்னி', 'குஞ்சொன்று', 'கண்டேன்', 'அக்னி', 'குஞ்சொன்று', 'கண்டேன்', '', 'அதை', 'அங்கொரு', 'காட்டிலோர்', 'பொந்திடை', 'வைத்தேன்', 'அக்னி', 'குஞ்சொன்று', 'கண்டேன்', '', 'அதை', 'அங்கொரு', 'காட்டிலோர்', 'பொந்திடை', 'வைத்தேன்', 'வெந்து', 'தணிந்தது', 'காடு', 'வெந்து', 'தணிந்தது', 'காடு', '', 'தழல்', 'வீரதிற்குஞ்சென்று', 'மூபென்றுமுண்டோ', 'தத்தரிகிட', 'தத்தரிகிட', 'தித்தோம்', 'தக', 'தத்தரிகிட', 'தத்தரிகிட', 'தித்தோம்', 'அக்னி', 'குஞ்சொன்று', 'கண்டேன்', '', 'அதை', 'அங்கொரு', 'காட்டிலோர்', 'பொந்திடை', 'வைத்தேன்', 'வெட்டி', 'அடிக்குது', 'மின்னல்']
Total Tokens: 2015
Unique Tokens: 830
Total Sequences: 1989
Sample Sequences அக்னி குஞ்சொன்று கண்டேன் அக்னி குஞ்சொன்று கண்டேன்  அதை அங்கொரு காட்டிலோர் பொந்திடை வைத்தேன் அக்னி குஞ்சொன்று கண்டேன்  அதை அங்கொரு காட்டிலோர் பொந்திடை வைத்தேன் வெந்து தணிந்தது காட

In [147]:
from numpy import array
from pickle import dump
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding

# load doc into memory
def load_doc(filename):
	# open the file as read only
	file = open(filename, 'r')
	# read all text
	text = file.read()
	# close the file
	file.close()
	return text

# load
in_filename = 'bharathi_sequences.txt'
doc = load_doc(in_filename)
lines = doc.split('\n')

# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)
sequences = tokenizer.texts_to_sequences(lines)
# vocabulary size
vocab_size = len(tokenizer.word_index) + 1



In [148]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
# define sequences
# pad sequence
sequences = pad_sequences(sequences, padding='post')
print(sequences)

[[189 188 135 ... 404   0   0]
 [188 135 189 ... 403   0   0]
 [135 189 188 ...   0   0   0]
 ...
 [ 63  64  26 ... 829  21  22]
 [ 64  26  65 ...  21  22 829]
 [ 26  65  66 ...  22 829  21]]


In [149]:
# separate into input and output
sequences = array(sequences)
sequences.shape

(1989, 26)

In [161]:
X, y = sequences[:,:-1], sequences[:,-1]
y = to_categorical(y, num_classes=vocab_size)
seq_length = X.shape[1]

# define model
model = Sequential()
model.add(Embedding(vocab_size, 50, input_length=seq_length))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())
# compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit model
model.fit(X, y, batch_size=128, epochs=25)

# save the model to file
model.save('model.h5')
# save the tokenizer
dump(tokenizer, open('tokenizer.pkl', 'wb'))

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 25, 50)            41500     
_________________________________________________________________
lstm_8 (LSTM)                (None, 25, 100)           60400     
_________________________________________________________________
lstm_9 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_8 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_9 (Dense)              (None, 830)               83830     
Total params: 276,230
Trainable params: 276,230
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/25
16/16 [==============================] - 1s 68ms/step - loss: 6.5898 - accuracy: 0.2956
Epoch 2/25

In [156]:
from random import randint
from pickle import load
from tensorflow.keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

# load doc into memory
def load_doc(filename):
	# open the file as read only
	file = open(filename, 'r')
	# read all text
	text = file.read()
	# close the file
	file.close()
	return text

# generate a sequence from a language model
def generate_seq(model, tokenizer, seq_length, seed_text, n_words):
	result = list()
	in_text = seed_text
	# generate a fixed number of words
	for _ in range(n_words):
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0]
		# truncate sequences to a fixed length
		encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
		# predict probabilities for each word
		yhat = model.predict_classes(encoded, verbose=0)
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text += ' ' + out_word
		result.append(out_word)
	return ' '.join(result)

# load cleaned text sequences
in_filename = 'bharathi_sequences.txt'
doc = load_doc(in_filename)
lines = doc.split('\n')
seq_length = len(lines[0].split()) - 1

# load the model
model = load_model('model.h5')

# load the tokenizer
tokenizer = load(open('tokenizer.pkl', 'rb'))

# select a seed text
seed_text = lines[randint(0,len(lines))]
print(seed_text + '\n')

# generate new text
generated = generate_seq(model, tokenizer, seq_length, seed_text, 50)
print(generated)

வெள்ளி பனிமலையின் மீதுலாவுவோம் அடி மேலை கடல் முழுதும் கப்பல் விடுவோம் பள்ளி தளம் அனைத்தும் கோவில் செய்குவோம் பள்ளி தளம் அனைத்தும் கோவில் செய்குவோம் எங்கள் பாரத தேசம் என்று தோள் கொட்டுவோம் எங்கள்

                                                 


In [154]:
seq_length

23

In [152]:
seed_text = 'என்று'
#seq_length = 10
generated = generate_seq(model, tokenizer, seq_length, seed_text, 50)
print(generated)